### ISSUE TITLE
Typo in model download instructions

### ISSUE THREAD

**Issue by eamadord** [uclnlp/cqd#3]
Hi! I'm trying to reproduce the code following the instructions on the README and I found an error in the instructions. 
In the instruction, a command for downloading and decompressing the model is provided. However, the decompressing instruction that follows does not refer to the models' file but to **cqd-data**. I've found that replacing the second line with 

```
% tar xvf cqd-models.tgz
```

solves this issue :)

**Comment by pminervini** [comment]
Hi @eamadord, thanks you for flagging this :)

You may also be interested in this another implementation of the method! https://github.com/snap-stanford/KGReasoning/pull/9 -- it allows you to benchmark it on more datasets

**Comment by pminervini** [comment]
Fixed! Thank you :)
