### ISSUE TITLE
The procedure of the t-norms and neural link prediction 

### ISSUE THREAD

**Issue by Joyrocky** [uclnlp/cqd#6]
I sorry to say that I could't really understand the procedure of the t-norms and neural link prediction when I studying the codes of this module😔  ,could you give some pseudo codes, math formulas or illustrations about this module. thx!😘 Looking forward for your reply😊

**Comment by pminervini** [comment]
Hi @Joyrocky, think of a t-norm as a generalisation of the logical AND!

It takes two scalar inputs `x, y ∈ [0, 1]`, and returns a value `z ∈ [0, 1]`. In case `x, y ∈ {0, 1}`, then the t-norm will behave like the logical AND (and return `z ∈ {0, 1}`). In case `x ∈ (0, 1)` or `y ∈ (0, 1)`, the t-norm may also return a value `z ∈ (0, 1)`.

There are many examples of t-norms -- check this out: https://en.wikipedia.org/wiki/T-norm#Prominent_examples
